name: Build project

on: [push, pull_request]

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unity-version:
          - 2022.3.10f1
        targetPlatform:
          - iOS # Build an iOS player.
          - Android # Build an Android .apk standalone app.
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.unity-version }}-${{ matrix.target-platform }}
          restore-keys: Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL}}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD}}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          unityVersion: ${{ matrix.unity-version }}
      - uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.unity-version }}-${{ matrix.target-platform }}
          path: build/${{ matrix.unity-version }}/${{ matrix.targetPlatform }}
